
services:
  db:
    image: mysql:8
    container_name: secure_directory_db
    restart: always
    environment:
      MYSQL_DATABASE: secure_directory
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"  # 🛑 Attention : ceci n'affecte pas le backend !
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - secure_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./secure-directory
    container_name: secure_directory_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy  # ✅ Attend que MySQL soit prêt avant de démarrer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/secure_directory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    volumes:
      - backend_logs:/app/logs
    networks:
      - secure_network

  frontend:
    build: ./frontend
    container_name: secure_directory_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - secure_network

volumes:
  mysql_data:
  backend_logs:

networks:
  secure_network:
